name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install 
        npm test
      env:
        CI: true
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v1
          - name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          - name: Build the tagged Docker image
            run: docker build . --file Dockerfile -t alfredobs/cicd:${{steps.vars.outputs.tag}}
          - name: Push the tagged Docker image
            run: docker push alfredobs97/cicd:${{steps.vars.outputs.tag}}
          
